name: build
on:
  push:
    branches: [ master ]
jobs:
  chobits:
    name: Build chobits
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Checkout deps
        run: |
          git submodule update --init --recursive
          cd ./deps
          ################################ ffmpeg
          sudo  apt install ffmpeg -y
          apt-cache madison ffmpeg
          ################################ libtorch
          # https://download.pytorch.org/libtorch/cpu/
          # https://download.pytorch.org/libtorch/cu126/
          wget  https://download.pytorch.org/libtorch/cpu/libtorch-cxx11-abi-shared-with-deps-2.7.0%2Bcpu.zip > /dev/null 2>&1
          unzip libtorch-cxx11-abi-shared-with-deps-2.7.0+cpu.zip > /dev/null 2>&1
      - name: Deploy chobits
        run: |
          gcc -v
          g++ -v
          cmake -version
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release
          make
          sudo make install
          make clean
